//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG_Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerMst
    {
        public int ImageID { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Title { get; set; }
    }
}
