//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG_Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiamondStock
    {
        public int StockMSTID { get; set; }
        public string StoneID { get; set; }
        public Nullable<decimal> Cts { get; set; }
        public string Location { get; set; }
        public string ReportNo { get; set; }
        public Nullable<int> CertificateCode { get; set; }
        public Nullable<int> ShapeCode { get; set; }
        public Nullable<int> SizeCode { get; set; }
        public Nullable<int> ColorCode { get; set; }
        public Nullable<int> PurityCode { get; set; }
        public Nullable<int> CutCode { get; set; }
        public Nullable<int> PolishCode { get; set; }
        public Nullable<int> SymmetryCode { get; set; }
        public Nullable<int> FlouCode { get; set; }
        public Nullable<decimal> Rap { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> Asking { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> SPer { get; set; }
        public Nullable<decimal> SRate { get; set; }
        public Nullable<decimal> SAmount { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> DepthPer { get; set; }
        public Nullable<decimal> TablePer { get; set; }
        public Nullable<decimal> CrownAngle { get; set; }
        public Nullable<decimal> CrownHeight { get; set; }
        public Nullable<decimal> PavAngle { get; set; }
        public Nullable<decimal> PavHeight { get; set; }
        public string KeytoSymbol { get; set; }
        public string VideoLink { get; set; }
        public string EyeClean { get; set; }
        public string Comments { get; set; }
        public string Girdle { get; set; }
        public string Culet { get; set; }
        public string Star { get; set; }
        public string Lower { get; set; }
        public string Milky { get; set; }
        public string CBlack { get; set; }
        public string SBlack { get; set; }
        public string CWhite { get; set; }
        public string SWhite { get; set; }
        public Nullable<int> HA { get; set; }
        public Nullable<bool> ResultVerify { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Inscription { get; set; }
        public Nullable<bool> Sale { get; set; }
        public Nullable<bool> Broker { get; set; }
        public Nullable<bool> Hold { get; set; }
        public Nullable<bool> Basket { get; set; }
        public Nullable<bool> Inquiry { get; set; }
        public Nullable<int> FancyColorCode { get; set; }
        public string BGM { get; set; }
        public string Diameter { get; set; }
        public Nullable<decimal> Ratio { get; set; }
        public Nullable<decimal> Table { get; set; }
        public Nullable<int> TOInclusion { get; set; }
        public Nullable<int> COInclusion { get; set; }
        public Nullable<int> POInclusion { get; set; }
        public Nullable<int> GOInclusion { get; set; }
    }
}
