//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG_Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryMst
    {
        public int InquiryId { get; set; }
        public string UserId { get; set; }
        public string InquiryName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Type { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsResolve { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CityMst CityMst { get; set; }
        public virtual CountryMst CountryMst { get; set; }
        public virtual StateMst StateMst { get; set; }
    }
}
