//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG_Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuMst()
        {
            this.UserMenuPermissionMsts = new HashSet<UserMenuPermissionMst>();
        }
    
        public int MenuMstId { get; set; }
        public Nullable<int> MainMenuMstId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> SortId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Icon { get; set; }
        public string URL { get; set; }
    
        public virtual MainMenuMst MainMenuMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMenuPermissionMst> UserMenuPermissionMsts { get; set; }
    }
}
